language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- pypy
install:
- pip install flake8==2.5.0
script:
- flake8 .
- python -m doctest README.md
- python -m doctest examples.MD
notifications:
  email: false